In [85]:
import tensorflow as tf

In [86]:
X = tf.constant([[[1, 2], [3, 4]]])
Y = tf.constant([[[6, 7], [8, 9]], [[1, 2], [3, 5]]])

In [87]:
X = tf.constant([[1, 2], [8, 9], [3, 2]])
Y = tf.constant([[1, 2], [8, 9]])

In [88]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [8, 9],
       [3, 2]])>

In [89]:
Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [8, 9]])>

In [90]:
XX = tf.reduce_sum(tf.square(X), 1)
YY = tf.reduce_sum(tf.square(Y), 1)
# XX is a row vector and YY is a column vector
XX = tf.reshape(XX, [-1, 1])
YY = tf.reshape(YY, [1, -1])

In [91]:
XX

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[  5],
       [145],
       [ 13]])>

In [92]:
YY

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[  5, 145]])>

In [93]:
XX + YY 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 10, 150],
       [150, 290],
       [ 18, 158]])>

In [94]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[  5,  26],
       [ 26, 145],
       [  7,  42]])>

In [95]:
result = XX + YY - 2 * tf.matmul(X, tf.transpose(Y))
result

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 0, 98],
       [98,  0],
       [ 4, 74]])>

In [96]:
min_i = tf.math.reduce_min(result)
max_i = tf.math.reduce_max(result)
a = (result - min_i) / (max_i - min_i)
a

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[0.        , 1.        ],
       [1.        , 0.        ],
       [0.04081633, 0.75510204]])>

In [97]:
result

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 0, 98],
       [98,  0],
       [ 4, 74]])>

In [98]:
tf.reduce_min(result, axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 4])>

In [99]:
tf.reduce_mean(tf.reduce_min(result, axis=1))

<tf.Tensor: shape=(), dtype=int32, numpy=1>